using TwitterTrends.Models;

namespace TwitterTrends
{
    public static class GetTrendingTime
    {
        public static List<TrendingTime> trendingTimes = new List<TrendingTime>()
        {
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 33 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 20 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 45 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 57 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 15 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 8 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 53 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 23 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 48 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 1 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 54 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 36 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 6 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 42 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 11 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 19 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 38 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 29 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 51 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 50 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 41 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 14 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 39 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 9 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 7 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 18 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 48 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 24 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 27 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 2 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 46 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 17 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 26 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 55 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 8 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 44 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 21 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 59 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 13 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 4 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 30 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 2 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 32 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 26 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 19 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 12 },
            new TrendingTime() { TrendingHour = 2, TrendingMinute = 21 },
            new TrendingTime() { TrendingHour = 1, TrendingMinute = 58 },
            new TrendingTime() { TrendingHour = 3, TrendingMinute = 36 },
            new TrendingTime() { TrendingHour = 4, TrendingMinute = 47 },
        };
    }
}
